version: '3.7'
services:
  dynamodb-local:
    container_name: 'dynamodb-local'
    build: ./docker/dynamodb-local/
    ports:
      - "7750:8000"
    volumes:
      - ".:/home/dynamodblocal/data"
    command: "-Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -dbPath ./data"

