version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: amazon/dynamodb-local:1.12.0
    working_directory: /go/src/github.com/moznion/aws-lambda-ddos-hangman
    steps:
      - checkout
      - run: make check

